changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

changesetIgnorePatterns:
  - '**/__tests__/**'

npmPublishAccess: public

packageExtensions:
  '@nrwl/devkit@*':
    peerDependencies:
      '@angular-devkit/architect': '*'
      rxjs: '*'
  '@nrwl/jest@*':
    dependencies:
      '@angular-devkit/architect': '>= 0.1200.0-rc.2 < 0.1300.0'
      dotenv: 10.0.0
    peerDependencies:
      jest: '*'
  '@nrwl/linter@*':
    dependencies:
      '@angular-devkit/architect': '>= 0.1200.0-rc.2 < 0.1300.0'
      rxjs: 6.6.7
  '@yarnpkg/esbuild-plugin-pnp@*':
    peerDependenciesMeta:
      esbuild:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-snuggery.cjs
    spec: '@yarnpkg/plugin-snuggery'
  - path: .yarn/plugins/@yarnpkg/plugin-snuggery-workspace.cjs
    spec: '@yarnpkg/plugin-snuggery-workspace'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'

preferDeferredVersions: true

yarnPath: .yarn/releases/yarn-3.0.0.cjs
