changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

changesetIgnorePatterns:
  - '**/__tests__/**'

enableScripts: false

npmPublishAccess: public

packageExtensions:
  '@nrwl/devkit@*':
    dependencies:
      '@angular-devkit/architect': '*'
    peerDependencies:
      rxjs: '*'
  '@yarnpkg/esbuild-plugin-pnp@*':
    peerDependenciesMeta:
      esbuild:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-snuggery.cjs
    spec: '@yarnpkg/plugin-snuggery'
  - path: .yarn/plugins/@yarnpkg/plugin-snuggery-workspace.cjs
    spec: '@yarnpkg/plugin-snuggery-workspace'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'

preferDeferredVersions: true

supportedArchitectures:
  os:
    - darwin
    - linux
    - win32
  cpu:
    - x64
    - arm64

yarnPath: .yarn/releases/yarn-3.2.0.cjs
