on:
  push:
    branches:
      - main
  pull_request:

name: 'Validation'
jobs:
  code-style:
    name: 'Code Style'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install
        shell: bash
        env:
          YARN_ENABLE_NETWORK: 0
        run: |
          yarn install --immutable --immutable-cache

      - name: 'Check for formatting errors (fix w/ "yarn prettier --write path/to/file")'
        run: |
          yarn prettier --check .
        shell: bash

      - name: 'Check for linting errors (fix w/ "yarn lint -c fix")'
        run: |
          yarn sn lint
        shell: bash

  build-unit:
    name: Build & Unit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Type-Check
        shell: bash
        run: |
          yarn tsc --noEmit

      - name: Build
        shell: bash
        run: |
          yarn sn build

      - name: 'Run tests'
        shell: bash
        run: |
          yarn sn test

  integration:
    name: 'Integration tests on node.js ${{matrix.node}} on ${{matrix.os}}'
    needs: build-unit
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node:
          - 12.x
          - 14.x
          - 16.x
          - 17.x

    steps:
      - uses: actions/checkout@v2

      - name: 'Use Node.js ${{matrix.node}}'
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}

      - name: 'Run tests'
        shell: bash
        run: |
          yarn sn test integration
